# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: postgress
    restart: always
    ports:
      - 8080:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: admin
      POSTGRES_DB: botpress

  botpress:
    image: botpress-cicd
    container_name: botpress
    restart: always
    ports:
      - 3000:3000
    environment:
      BPFS_STORAGE: database
      AUTO_MIGRATE: "true" 
      CI_EMAIL: eduardo.elliot.martinez.palomino@uabc.edu.mx
      CI_PASSWORD: "!Hola1234"
      DATABASE_URL: postgres://admin:mysecretpassword@postgress:5432/botpress
    depends_on:
      - db